Traceback (most recent call last):
  File "/home/keenanmanpearl/Desktop/mitocheck_td-vae/main_train.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
(9, 3300)
Traceback (most recent call last):
  File "/home/keenanmanpearl/Desktop/mitocheck_td-vae/main_train.py", line 69, in <module>
    tdvae.forward(images)
  File "/home/keenanmanpearl/Desktop/mitocheck_td-vae/model.py", line 305, in forward
    self.processed_x = self.process_x(self.x)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keenanmanpearl/miniconda3/envs/pyimagej/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keenanmanpearl/Desktop/mitocheck_td-vae/model.py", line 56, in forward
    t = torch.relu(self.fc1(input))
                   ^^^^^^^^^^^^^^^
  File "/home/keenanmanpearl/miniconda3/envs/pyimagej/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/keenanmanpearl/miniconda3/envs/pyimagej/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (180x3300 and 3417x3417)
